### ISSUE TITLE
wildcard time parsing

### ISSUE THREAD

**Issue by devensiv** [devensiv/bar_calendar#1]
# Issue
Wildcards get replaced with their corresponding parts from the current time.

# Possible solve
Add an offset that is toggled by a part being wildcard & event time without offset being in the past
Do only increment the smallest wildcard parameter (extra check for day/week/month "overflow")

**Comment by DEVensiv** [comment]
[wildcard parsing.pdf](https://github.com/DEVensiv/bar_calendar/files/6717380/wildcard.parsing.pdf)

**Comment by devensiv** [comment]
![image](https://user-images.githubusercontent.com/35898914/123451849-2b3ff580-d5de-11eb-8598-ed41c94be6c2.png)
